services:
  backend:
    build:
      context: ./backend
    command: ./wait-for-db.sh db python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: eggly_db
      POSTGRES_USER: eggly_user
      POSTGRES_PASSWORD: eggly_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    image: node:20-alpine
    working_dir: /app
    environment:
      - IS_DOCKER=true
      - NEXT_PUBLIC_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

volumes:
  pgdata:
